config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :years, only: [:index, :show, :create] do
    member do
      post :extend
      get :for_date
    end
    resources :weeks, only: [:index, :show]
    resources :rows, only: [:create]
  end

  resources :days, only: [] do
    member do
      post 'items'
    end
  end

  resources :shares, only: [:show]

  root to: "years#index"
end

app/models/week.rb
class Week < ApplicationRecord
  extend FriendlyId
  friendly_id :number, use: :finders

  belongs_to :year

  has_many :days, dependent: :destroy

  def self.populate(number, start_date)
    week = create(number: number, start_date: start_date)
    %w{ Monday Tuesday Wednesday Thursday Friday}.each_with_index do |day, i|
      week.days.create(name: day, date: start_date + i.days)
    end

    week
  end

  def prev_week
    year.weeks.find_by(number: number - 1)
  end

  def next_week
    year.weeks.find_by(number: number + 1)
  end
end

app/controllers/weeks_controller.rb
class WeeksController < ApplicationController
  before_action :authenticate_user!

  def show
    year_id = params[:year_id]
    year = current_user.years.find_by(id: year_id)
    year ||= current_user.years.find_by(name: year_id)
    year ||= current_user.collaborating_years.find_by(id: year_id)
    year ||= current_user.collaborating_years.find_by(name: year_id)

    raise ActiveRecord::RecordNotFound.new unless year

    @week = year.weeks.find(params[:id])
    @days = @week.days.order(:date)
    @rows = year.rows
    @items = Item.where(row: @rows, day: @days).group_by(&:row_id)
  end
end

app/views/weeks/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-1 grade">
      <div class="header cell"><br/>Name</div>
    </div>
    <% @days.each do |day| %>
      <% col_width = day.today? ? 3 : 2 %>
      <div class="col-md-<%= col_width %>">
        <div class="header cell <%= "text-info" if day.today? %>">
          <%= day.name %><br/><%= day.date.strftime("%-m/%d") %>
        </div>
      </div>
    <% end %>
  </div>
  <% @rows.each do |row| %>
    <% row_items = @items.fetch(row.id, []).group_by(&:day_id) %>
    <div class="row">
      <div class="col-md-1 grade">
        <div class="cell"><%= row.name %></div>
      </div>
      <% @days.each do |day| %>
        <% col_width = day.today? ? 3 : 2 %>
        <div class="col-md-<%= col_width %>">
          <div class="day cell <%= "bg-info" if day.today? %>">
            <ul>
              <% if row_items.fetch(day.id, []).any? %>
                <% row_items[day.id].each do |item| %>
                  <li>
                    <% if item.url %>
                      <%= link_to item.text, item.url %>
                    <% else %>
                      <%= item.text %>
                    <% end %>
                  </li>
                <% end %>
              <% else %>
                <li>Dbl click to add items.</li>
              <% end %>
            </ul>
            <%= form_tag items_day_path(day), class: "items_form" do %>
              <%= text_area_tag "items", row_items.fetch(day.id, []).map{|item| item.text + (item.url ? " [#{item.url}]" : "") }.join("\n\n"), rows: 5 %>
              <br>
              <%= hidden_field_tag :row_id, row.id %>
              <%= submit_tag "Update", class: "btn btn-primary" %>
              <%= submit_tag "Cancel", class: "btn btn-danger" %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>

  <% if @rows.any? %>
    <div class="row">
      <div class="col-md-1 navigation-prev">
        <% if @week.prev_week %>
          <%= link_to "< Previous", year_week_url(@week.year, @week.prev_week) %>
        <% end %>
      </div>
      <% offset = @week.days.any?(&:today?) ? 4 : 3 %>
      <div class="col-md-2 col-md-offset-<%= offset %>">
        <%= form_tag for_date_year_path(@week.year), class: "navigation-form", method: :get do %>
          <div class="input-group">
            <%= text_field_tag "date", "", placeholder: "Jump to date", class: "form-control" %>
            <span class="input-group-btn"><%= submit_tag "Go", class: "btn btn-primary" %></span>
          </div>
        <% end %>
      </div>
      <div class="col-md-1 col-md-offset-4 navigation-next">
        <% if @week.next_week %>
          <%= link_to "Next >", year_week_url(@week.year, @week.next_week) %>
        <% else %>
          <%= form_tag extend_year_path(@week.year), method: :post, id: "add-weeks-form" do %>
            <%= hidden_field_tag "number_of_weeks", "", id: "add-weeks-number" %>
          <% end %>
          <%= link_to "Add More Weeks", "#", id: "add-weeks-link" %>
        <% end %>
      </div>
    </div>
  <% end %>

  <div class="row">
    <%= form_tag year_rows_path(@week.year), method: :post, id: "add-row-form" do %>
      <%= hidden_field_tag "name", "", id: "add-row-name" %>
    <% end %>
    <% col_width = @week.days.any?(&:today?) ? 12 : 11 %>
    <div class="col-md-<%= col_width %>">
      <%= submit_tag "+ Add Row", class: "btn btn-primary", style: "width: 100%;", id: "btn-add-row" %>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(function() {
    var monday = new Date(<%= @days.first.date.year %>, <%= @days.first.date.month - 1 %>, <%= @days.first.date.day %>);
    $("#date").datepicker({dateFormat: "yy-mm-dd", defaultDate: monday});

    var week = new Week();
    week.init();
  });
</script>